### ISSUE TITLE
Django 1.9 compatibility - AppRegistryNotReady

### ISSUE THREAD

**Issue by theskumar** [lambdalisue/django-permission#48]
After upgrading to django 1.9 and running `python manage.py check`, I get the following error:
```
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/path/to/virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/path/to/virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "/path/to/virtualenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/path/to/virtualenv/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/path/to/virtualenv/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/path/to/virtualenv/lib/python2.7/site-packages/permission/__init__.py", line 9, in <module>
    from permission.utils.logics import add_permission_logic
  File "/path/to/virtualenv/lib/python2.7/site-packages/permission/utils/logics.py", line 6, in <module>
    from permission.logics import PermissionLogic
  File "/path/to/virtualenv/lib/python2.7/site-packages/permission/logics/__init__.py", line 7, in <module>
    from permission.logics.author import AuthorPermissionLogic
  File "/path/to/virtualenv/lib/python2.7/site-packages/permission/logics/author.py", line 6, in <module>
    from permission.conf import settings
  File "/path/to/virtualenv/lib/python2.7/site-packages/permission/conf.py", line 10, in <module>
    from permission.handlers import LogicalPermissionHandler
  File "/path/to/virtualenv/lib/python2.7/site-packages/permission/handlers.py", line 5, in <module>
    from permission.utils.permissions import get_app_perms
  File "/path/to/virtualenv/lib/python2.7/site-packages/permission/utils/permissions.py", line 9, in <module>
    from django.contrib.auth.models import Permission
  File "/path/to/virtualenv/lib/python2.7/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/path/to/virtualenv/lib/python2.7/site-packages/django/contrib/auth/base_user.py", line 49, in <module>
    class AbstractBaseUser(models.Model):
  File "/path/to/virtualenv/lib/python2.7/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/path/to/virtualenv/lib/python2.7/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/path/to/virtualenv/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by theskumar** [comment]
The issues seems to be `permission/utils/permissions.py", line 9` where it is trying to import `from django.contrib.auth.models import Permission` during project setup.

**Comment by lambdalisue** [comment]
Hum... Thanks for reporting. We will check it. Probably [the line](https://github.com/lambdalisue/django-permission/blob/master/src/permission/utils/permissions.py#L9) should be loaded in each functions I guess.

**Comment by JanMalte** [comment]
A second compatibility break is in permission/compat.py which is throwing:
```cannot import name 'add_to_builtins```

```python
    try:
        from django.template.base import add_to_builtins
    except ImportError:
        from django.template.loader import add_to_builtins
```

https://docs.djangoproject.com/en/dev/releases/1.9/#django-template-base-add-to-builtins-is-removed

**Comment by lambdalisue** [comment]
We are working on this https://github.com/lambdalisue/django-permission/pull/50 :-)
