### ISSUE TITLE
ImportError if django 1.9 AppConfig is used for installed apps

### ISSUE THREAD

**Issue by JanMalte** [lambdalisue/django-permission#60]
if I add `permission.autodiscover()` to my urls.py, the following exception is thrown, if the Django 1.9 AppConfig ist used for my apps. If the `.apps.ProjectAppConfig` is removed, the exception does not occur.

``` python
INSTALLED_APPS = [
    ...
    'project_app.apps.ProjectAppConfig',  # Not working
    # 'project_app',  # Working
]
```

``` python
Traceback (most recent call last):
  File "/project/env/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/project/env/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/project/env/lib/python3.4/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/project/env/lib/python3.4/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/project/env/lib/python3.4/site-packages/django/core/checks/urls.py", line 10, in check_url_config
    return check_resolver(resolver)
  File "/project/env/lib/python3.4/site-packages/django/core/checks/urls.py", line 19, in check_resolver
    for pattern in resolver.url_patterns:
  File "/project/env/lib/python3.4/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/project/env/lib/python3.4/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/project/env/lib/python3.4/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/project/env/lib/python3.4/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/project/env/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/project/src/project/urls.py", line 21, in <module>
    permission.autodiscover()
  File "/project/env/lib/python3.4/site-packages/permission/utils/autodiscover.py", line 19, in autodiscover
    mod = import_module(app)
  File "/project/env/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2221, in _find_and_load_unlocked
ImportError: No module named 'project.apps.ProjectConfig'; 'project.apps' is not a package
```

This hack fixes the error for now:

``` python
#/project/env/lib/python3.4/site-packages/permission/utils/autodiscover.py:18
    for app in settings.INSTALLED_APPS:
        if '.apps.' in app:
            app = app.split('.')[0]
        mod = import_module(app)
```

**Comment by JanMalte** [comment]
Maybe a better fix would be
```
#/project/env/lib/python3.4/site-packages/permission/utils/autodiscover.py:18
    for app in settings.INSTALLED_APPS:
        if '.' in app:
            mod = import_string(app)
        else:
            mod = import_module(app)
```

**Comment by lambdalisue** [comment]
Aha, yeah the autodiscover feature was developed when there were not appconfig thing...
Probably there should be a way to use autodiscover with appconfig but for now, I don't know the way.

What happen if you don't use autodiscover feature and manually assign in `models.py`? I'm the one who made this but I know sometime these kind of **auto** feature makes things too complicated...

**Comment by JanMalte** [comment]
Maybe you could use `django.utils.module_loading.autodiscover_modules` for autodiscovering permissions. Maybe I can take a look at it in the next days.

**Comment by vosi** [comment]
django admin autodiscovery uses django.utils.module_loading.autodiscover_modules for the same purposes

**Comment by JanMalte** [comment]
More and more apps are using the AppConfig feature which will break if django-permission is used. Please add any of the stated solutions and create a new release as soon as possible. Thanks in advance.

**Comment by EliotBerriot** [comment]
I'm not directly impacted by this bug, but as the maintainer of django-dynamic-preferences, I was also impacted by this (we needed to autodiscover some modules in installed apps). 

I never used `django.utils.module_loading.autodiscover_modules`, but we solved this issue by grabbing the app paths from `django.apps.apps`, as showed [here](https://github.com/EliotBerriot/django-dynamic-preferences/blob/develop/dynamic_preferences/apps.py#L19):

```þython
from django.apps import apps
app_names = [app.name for app in apps.app_configs.values()]
for module in app_names:
    # your import logic
```

This way, you can get the real package path for each app (and not the AppConfig path declared in `INSTALLED_APPS` which break your import logic).

Just my 2 cts ;)

**Comment by lambdalisue** [comment]
@giginet Do you have time to investigate nd fix this?

**Comment by lambdalisue** [comment]
@JanMalte @vosi @EliotBerriot sorry for late. I take @EliotBerriot 's way and it fix the problem 👍
